import React, { useEffect, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import {
  Box,
  Container,
  Typography,
  Card,
  CardContent,
  CardMedia,
  Button,
  CircularProgress,
  Chip,
  
} from '@mui/material'
import { motion } from 'framer-motion'

interface SentimentBreakdown {
  positive: number
  neutral: number
  negative: number
}

interface AnalysisResult {
  summary: string
  tone: string
  rating: number
  sentiment_breakdown: SentimentBreakdown
  pros: string[]
  cons: string[]
  review_count: number
}

const Dashboard: React.FC = () => {
  const location = useLocation()
  const navigate = useNavigate()
  const productURL = (location.state as any)?.productURL

  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [result, setResult] = useState<AnalysisResult | null>(null)
  const [preview, setPreview] = useState<{ image?: string; title?: string; description?: string; url: string } | null>(null)
  const [typedText, setTypedText] = useState('')
  const fullText = 'Summary generated by AI 🤖'

  // typing animation for header
  useEffect(() => {
    let i = 0
    setTypedText('')
    const id = setInterval(() => {
      setTypedText((t) => t + fullText.charAt(i))
      i += 1
      if (i >= fullText.length) {
        clearInterval(id)
      }
    }, 30)
    return () => clearInterval(id)
  }, [])

  // debug: log mount and productURL
  useEffect(() => {
    // eslint-disable-next-line no-console
    console.log('Dashboard mounted', { productURL })
    return () => {
      // eslint-disable-next-line no-console
      console.log('Dashboard unmounted')
    }
  }, [productURL])

  // debug: log result updates
  useEffect(() => {
    // eslint-disable-next-line no-console
    console.log('Dashboard result changed', { result })
  }, [result])

  // mock analyze product (replace with real API call)
  useEffect(() => {
    if (!productURL) {
      setLoading(false)
      setError('No product URL provided')
      return
    }

    setLoading(true)
    setError('')

    // simulate network call
    const t = setTimeout(() => {
      // create a simple preview from the URL
      try {
        setPreview({
          image: undefined,
          title: `Product from ${new URL(productURL).hostname}`,
          description: 'Auto-generated preview (mock).',
          url: productURL,
        })
      } catch (e) {
        setPreview({ title: 'Product', description: 'Preview not available', url: productURL })
      }

      const mock: AnalysisResult = {
        summary: 'Customers like the build quality and value for money. Some report issues with battery life.',
        tone: 'Informative',
        rating: 4.1,
        sentiment_breakdown: { positive: 68, neutral: 20, negative: 12 },
        pros: ['Build quality', 'Value', 'Design'],
        cons: ['Battery life', 'Occasional glitches'],
        review_count: 348,
      }
      setResult(mock)
      setLoading(false)
    }, 900)

    return () => clearTimeout(t)
  }, [productURL])

  const renderSentimentBar = (sentiments: SentimentBreakdown) => {
    const total = sentiments.positive + sentiments.neutral + sentiments.negative || 1
    return (
      <Box sx={{ display: 'flex', gap: 1, alignItems: 'center', mt: 1, mb: 1 }}>
        <Box sx={{ flex: sentiments.positive / total, height: 12, backgroundColor: '#4caf50', borderRadius: '6px' }} />
        <Box sx={{ flex: sentiments.neutral / total, height: 12, backgroundColor: '#9e9e9e', borderRadius: '6px' }} />
        <Box sx={{ flex: sentiments.negative / total, height: 12, backgroundColor: '#f44336', borderRadius: '6px' }} />
      </Box>
    )
  }

  return (
    <Box
      sx={{
        minHeight: '100vh',
        background: 'linear-gradient(135deg, #e0f7fa 0%, #f3e5f5 100%)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        py: 6,
      }}
    >
      <Container>
        <Typography
          variant="h4"
          sx={{
            fontWeight: 'bold',
            mb: 2,
            textAlign: 'center',
            color: '#333',
          }}
        >
          Review Analysis Dashboard
        </Typography>

        <Card
          sx={{
            backgroundColor: '#ffffff',
            borderRadius: '20px',
            boxShadow: '0 0 20px rgba(63,81,181,0.15)',
            mb: 4,
            overflow: 'hidden',
          }}
        >
          {preview ? (
            <Box sx={{ display: 'flex', flexDirection: 'row', p: 2 }}>
              {preview.image && (
                <CardMedia component="img" src={preview.image} alt={preview.title} sx={{ width: 150, height: 150, borderRadius: '12px', objectFit: 'cover', mr: 2 }} />
              )}
              <Box>
                <Typography variant="h6">{preview.title}</Typography>
                <Typography variant="body2" sx={{ color: 'gray', mb: 1, maxWidth: '400px' }}>{preview.description}</Typography>
                <Button variant="outlined" color="primary" component="a" href={preview.url} target="_blank" rel="noopener noreferrer">
                  View Product
                </Button>
              </Box>
            </Box>
          ) : (
            <Box sx={{ p: 2, textAlign: 'center' }}>
              <Typography variant="body2">
                <strong>Product URL:</strong>{' '}
                <a href={productURL} target="_blank" rel="noopener noreferrer">{productURL}</a>
              </Typography>
            </Box>
          )}
        </Card>

        {loading ? (
          <Box textAlign="center" mt={5}>
            <CircularProgress />
            <Typography variant="body2" sx={{ mt: 2 }}>Analyzing reviews...</Typography>
          </Box>
        ) : error ? (
          <Typography color="error" sx={{ textAlign: 'center', mt: 3 }}>{error}</Typography>
        ) : (
          result && (
            <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.5 }}>
              <Card sx={{ backgroundColor: '#ffffff', borderRadius: '20px', mt: 3, p: 3, boxShadow: '0 0 20px rgba(63,81,181,0.2), 0 0 40px rgba(156,39,176,0.1)' }}>
                <CardContent>
                  <Typography variant="h6" sx={{ fontWeight: 'bold', mb: 1, color: '#3f51b5', textAlign: 'center' }}>{typedText}</Typography>

                  <Typography variant="body1" sx={{ mb: 3, textAlign: 'center' }}>{result.summary}</Typography>

                  <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' }, gap: 2 }}>
                    <Box>
                      <Typography variant="body1"><strong>Tone:</strong> {result?.tone}</Typography>
                      <Typography variant="body1"><strong>Rating:</strong> ⭐ {result?.rating}/5</Typography>

                      <Typography variant="body1" sx={{ mt: 2 }}><strong>Sentiment Breakdown:</strong></Typography>
                      {renderSentimentBar(result?.sentiment_breakdown ?? { positive: 0, neutral: 0, negative: 0 })}
                      <Typography variant="body2">Positive: {result?.sentiment_breakdown?.positive ?? 0}% | Neutral: {result?.sentiment_breakdown?.neutral ?? 0}% | Negative: {result?.sentiment_breakdown?.negative ?? 0}%</Typography>
                    </Box>

                    <Box>
                      <Typography variant="body1" sx={{ fontWeight: 'bold', mb: 1 }}>Pros:</Typography>
                      {(result?.pros ?? []).map((p, i) => (
                        <Chip key={i} label={p} color="success" variant="outlined" sx={{ mr: 1, mb: 1 }} />
                      ))}

                      <Typography variant="body1" sx={{ fontWeight: 'bold', mt: 2, mb: 1 }}>Cons:</Typography>
                      {(result?.cons ?? []).map((c, i) => (
                        <Chip key={i} label={c} color="error" variant="outlined" sx={{ mr: 1, mb: 1 }} />
                      ))}
                    </Box>
                  </Box>

                  <Typography variant="body2" sx={{ mt: 3, textAlign: 'right', fontStyle: 'italic', color: '#555' }}>Based on {result?.review_count ?? 0} reviews analyzed.</Typography>
                </CardContent>
              </Card>
            </motion.div>
          )
        )}

        <Box textAlign="center" mt={4}>
          <Button variant="outlined" onClick={() => navigate('/')}>Back</Button>
        </Box>
      </Container>
    </Box>
  )
}

export default Dashboard
